### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument max in method wrapper_clamp_Tensor)

### ISSUE THREAD

**Issue by kaiwendulantediyiren** [iscyy/ultralyticsPro#61]
Swin_V2运行报这个错，想问问要怎么解决呢？

**Comment by yang-0201** [comment]
训练命令加了“--device 0”嘛

**Comment by kaiwendulantediyiren** [comment]
> 训练命令加了“--device 0”嘛

加了，一样报这个错

**Comment by kaiwendulantediyiren** [comment]
> 训练命令加了“--device 0”嘛
你的能跑起来吗？

**Comment by kaiwendulantediyiren** [comment]
Who can solve this problem？

**Comment by yang-0201** [comment]
You can chat with me privately to see what your problem is, Wechat: 1111554

**Comment by iscyy** [comment]
You can try
!pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by kaiwendulantediyiren** [comment]
It has been resolved. You can replace the torch and cuda versions.
!pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f

**Comment by lixiangMindSpore** [comment]
> It has been resolved. You can replace the torch and cuda versions. !pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f

你下发命令是什么？

**Comment by zxp771** [comment]
@iscyy 
hi,i followed you suggestion,but the error still there.
![image](https://user-images.githubusercontent.com/35118859/228462337-b969ad74-634a-4755-9737-bfa62c47e36d.png)

Traceback (most recent call last):
  File "D:\yy\yolov7-main\test.py", line 320, in <module>
    test(opt.data,
  File "D:\yy\yolov7-main\test.py", line 88, in test
    model(torch.zeros(1, 3, imgsz, imgsz).to(device).type_as(next(model.parameters())))  # run once
  File "D:\Anaconda\envs\yolo-hornet\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\yy\yolov7-main\utils\torch_utils.py", line 372, in forward
    out = self.model(x)
  File "D:\Anaconda\envs\yolo-hornet\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
D:\yy\yolov7-main\models\common.py(1688): forward
D:\Anaconda\envs\yolo-hornet\lib\site-packages\torch\nn\modules\module.py(1039): _slow_forward
D:\Anaconda\envs\yolo-hornet\lib\site-packages\torch\nn\modules\module.py(1051): _call_impl
D:\yy\yolov7-main\models\common.py(1828): forward
D:\Anaconda\envs\yolo-hornet\lib\site-packages\torch\nn\modules\module.py(1039): _slow_forward
D:\Anaconda\envs\yolo-hornet\lib\site-packages\torch\nn\modules\module.py(1051): _call_impl
D:\Anaconda\envs\yolo-hornet\lib\site-packages\torch\nn\modules\container.py(139): forward
D:\Anaconda\envs\yolo-hornet\lib\site-packages\torch\nn\modules\module.py(1039): _slow_forward
D:\Anaconda\envs\yolo-hornet\lib\site-packages\torch\nn\modules\module.py(1051): _call_impl
D:\yy\yolov7-main\models\common.py(1867): forward
D:\Anaconda\envs\yolo-hornet\lib\site-packages\torch\nn\modules\module.py(1039): _slow_forward
D:\Anaconda\envs\yolo-hornet\lib\site-packages\torch\nn\modules\module.py(1051): _call_impl
D:\yy\yolov7-main\models\common.py(516): forward
D:\Anaconda\envs\yolo-hornet\lib\site-packages\torch\nn\modules\module.py(1039): _slow_forward
D:\Anaconda\envs\yolo-hornet\lib\site-packages\torch\nn\modules\module.py(1051): _call_impl
D:\yy\yolov7-main\models\yolo.py(625): forward_once
D:\yy\yolov7-main\models\yolo.py(599): forward
D:\Anaconda\envs\yolo-hornet\lib\site-packages\torch\nn\modules\module.py(1039): _slow_forward
D:\Anaconda\envs\yolo-hornet\lib\site-packages\torch\nn\modules\module.py(1051): _call_impl
D:\Anaconda\envs\yolo-hornet\lib\site-packages\torch\jit\_trace.py(952): trace_module
D:\Anaconda\envs\yolo-hornet\lib\site-packages\torch\jit\_trace.py(735): trace
D:\yy\yolov7-main\utils\torch_utils.py(362): __init__
D:\yy\yolov7-main\test.py(63): test
D:\yy\yolov7-main\test.py(320): <module>
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
